### ISSUE TITLE
Automating AppImage installation and desktop entry

### ISSUE THREAD

**Issue by wiktor2200** [fluks/taskcoach-appimage#3]
Hello, first of all cheers for your good job creating AppImage for Taskcoach :trophy:  
I've prepared Task Coach installation script in my script bundle. It consists of downloading AppImage + icon than setting desktop entry based on `firejail` usage. I thought you might be interested in adding "Desktop Entry" to your README. 
Here's a link: https://github.com/wiktor2200/Ubuntu-firstrun-config/blob/master/scripts/install-taskcoach

You you think, it's not needed just close this issue :)

**Comment by fluks** [comment]
Thanks. I don't think adding a desktop entry is related to this repo that much, this is only about the AppImage.
